In [ ]:
#Al ser un algoritmo de clasificación se enfocó en validar si el precio de una fruta alojado
#en un dataset es igual o menor al precio deseado por el usuario
#Se importa la libreria
import pandas as pd

# se Carga el archivo CSV
data = pd.read_csv("sample_data/frutas.csv")
data

        fruta  precio
0     naranja       3
1     manzana       4
2      guineo       5
3   mandarina       6
4    aguacate       1
5       mango       2
6      sandia       4
7      zapote       7
8         uva       4
9      papaya       5
10       mora       7
11    ciruela       3

In [ ]:
# Definimos la función para buscar el precio de una fruta
def buscar_precio(fruta, precio):
    # Se filtra el DataFrame por la fruta deseada (búsqueda)
    fruta_data = data[data['fruta'] == fruta]

    # Verificar si el precio de la fruta encontrada es mayor al precio deseado (clasificación)
    if len(fruta_data) > 0 and fruta_data['precio'].values[0] > precio:
        return True
    else:
        return False

In [ ]:
# búsqueda por favor escriba la fruta y el precio deseado
fruta_buscada = "mango"
precio_deseado = 1
resultado = buscar_precio(fruta_buscada, precio_deseado)

# Resultado de lo elegido en el árbol
if resultado:
    print("El precio de la fruta", fruta_buscada, "es mayor a", precio_deseado,"No alcanza")
else:
    print("El precio de la fruta", fruta_buscada, "es menor o igual a", precio_deseado, "Compre es saludable")

El precio de la fruta mango es mayor a 1 No alcanza